# Get information about PROUNI grades

In [2]:
%matplotlib inline
import pandas as pd

data = pd.read_csv('./assets/CURSOS_PROUNI_NOTA_DE_CORTE_2018.csv')
data.head()

,uf_busca,cidade_busca,universidade_nome,campus_nome,nome,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,AC,Acrelandia,Universidade Paulista - UNIP,ACRELANDIA - Centro,Administração,Bacharelado,Curso a Distância,289.0,1.0,1.0,NaN,NaN,572.74,548.0,NaN,NaN
1,AC,Cruzeiro do Sul,Centro Universitário Internacional - Uninter -...,PAP CRUZEIRO DO SUL - Centro,Administração,Bacharelado,Curso a Distância,298.0,1.0,NaN,NaN,NaN,646.14,NaN,NaN,NaN
2,AC,Cruzeiro do Sul,Faculdade Educacional da Lapa - FAEL,AC - CRUZEIRO DO SUL - POLO EAD - CENTRO,Administração,Bacharelado,Curso a Distância,325.0,NaN,NaN,1.0,NaN,NaN,NaN,577.62,NaN
3,AC,Cruzeiro do Sul,Universidade Paulista - UNIP,CRUZEIRO DO SUL - Centro,Administração,Bacharelado,Curso a Distância,319.0,1.0,NaN,NaN,NaN,616.68,NaN,NaN,NaN
4,AC,Rio Branco,Centro Universitário Internacional - Uninter -...,PAP RIO BRANCO - Bosque,Administração,Bacharelado,Curso a Distância,298.0,NaN,NaN,1.0,NaN,NaN,NaN,569.00,NaN

## View data specification

In [11]:
# Data types of columns
data.dtypes

uf_busca                 object
cidade_busca             object
universidade_nome        object
campus_nome              object
nome                     object
grau                     object
turno                    object
mensalidade             float64
bolsa_integral_cotas    float64
bolsa_integral_ampla    float64
bolsa_parcial_cotas     float64
bolsa_parcial_ampla     float64
nota_integral_ampla     float64
nota_integral_cotas     float64
nota_parcial_ampla      float64
nota_parcial_cotas      float64
dtype: object

We can has one idea about the dimensions of archive CSV. Do this just calling the attribute `shape` in dataframe variable.

He will return (x, y), where:
* `x` = amount rows
* `y` = amout columns

In [10]:
data.shape

(41447, 16)

## Null values in Dataset
When we are analysing data, its probably that find null values presents on rows. Our study of PROUNI Grades, we have null values. View the table below after call the method `info()`:

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41447 entries, 0 to 41446
Data columns (total 16 columns):
uf_busca                41447 non-null object
cidade_busca            41447 non-null object
universidade_nome       41447 non-null object
campus_nome             41447 non-null object
nome                    41447 non-null object
grau                    41447 non-null object
turno                   41447 non-null object
mensalidade             41447 non-null float64
bolsa_integral_cotas    32520 non-null float64
bolsa_integral_ampla    25404 non-null float64
bolsa_parcial_cotas     8828 non-null float64
bolsa_parcial_ampla     13041 non-null float64
nota_integral_ampla     32520 non-null float64
nota_integral_cotas     16802 non-null float64
nota_parcial_ampla      16350 non-null float64
nota_parcial_cotas      5519 non-null float64
dtypes: float64(9), object(7)
memory usage: 5.1+ MB

Notice that have aritimetical diference between `mensalidade` and `bolsa_integral_cotas`. Its means that in the column `bolsa_integral_cotas`, has values not entered.

## Groupment Command
If you need group results, use the dataframe method `groupby(x)[y].z()`, where we can interpreter:

> Agroup one attribute x by y. However, apply the rule z (min, max, count, etc)

**Example: Agroup the attribute `uf_busca` by highest 'mensalidade`**

Solution: 
```python
data.groupby('uf_busca')['mensalidade'].max()
```

## Questions

**1. Courses Amount by `uf_busca`**

In [14]:
data['uf_busca'].value_counts()

SP    11533
MG     4175
PR     3918
RS     3060
BA     2505
SC     2195
RJ     1442
GO     1278
PA     1201
PE     1148
MT     1063
DF     1063
ES      825
CE      816
MS      785
MA      679
PB      596
RO      463
AM      429
PI      405
TO      343
RN      342
AL      327
SE      323
AP      219
AC      203
RR      111
Name: uf_busca, dtype: int64

**2. Return course with higher montly payment  **

In [44]:
data[data['mensalidade'] == data['mensalidade'].max()][['uf_busca','cidade_busca','grau','nota_integral_ampla','mensalidade']]

      uf_busca  cidade_busca         grau  nota_integral_ampla  mensalidade
31987       MS  Campo Grande  Bacharelado               740.22      9999.99

**3. Group the courses per grades (`nota_integral_ampla`)**

In [55]:
data.groupby('nome')['nota_integral_ampla'].unique()

nome
Administração                            [572.74, 646.14, nan, 616.68, 612.24, 608.18, ...
Administração Pública                    [577.44, 544.02, 625.18, 599.14, 578.68, 581.5...
Administração de Empresas                                                         [638.42]
Administração de Recursos Humanos        [564.42, 555.44, 559.9, 566.18, 564.8, 550.1, ...
Agroindústria                                                                     [570.52]
Agronegócio                              [557.34, 584.14, 573.08, 634.98, 577.54, nan, ...
Agronomia                                [653.18, 606.04, 614.68, 603.08, 627.6, 627.52...
Agropecuária                                                                      [579.02]
Alimentos                                                 [562.34, 562.82, 560.72, 547.72]
Análise e Desenvolvimento de Sistemas    [613.14, 598.94, nan, 615.54, 579.96, 589.4, 5...
Arqueologia                                                                       [593.94]
Arquitetura e Urbanismo                  [720.42, 614.0, 634.8, 619.22, 619.06, 654.18,...
Artes                                                                             [587.34]
Artes Cênicas                                                             [641.26, 717.06]
Artes VIsuais                            [565.48, nan, 567.0, 579.16, 598.6, 536.34, 56...
Audiovisual                                                               [667.74, 655.66]
Automação Industrial                     [599.38, 602.8, nan, 624.1, 601.2, 574.96, 546...
Banco de Dados                           [600.74, nan, 621.76, 450.0, 591.8, 602.36, 55...
Biblioteconomia                          [593.38, 545.92, 619.54, 594.04, 574.12, 594.3...
Biocombustíveis                                                           [591.38, 563.64]
Biologia                                 [582.14, 584.56, 599.26, 618.46, 618.08, 625.4...
Biomedicina                              [nan, 679.04, 663.7, 651.96, 660.9, 617.4, 649...
Biotecnologia                                                                 [nan, 676.9]
Cinema e Audiovisual                                 [nan, 641.34, 670.48, 637.68, 705.32]
Ciência Econômica                                                    [569.84, 590.84, nan]
Ciência Política                         [nan, 619.36, 575.02, 640.58, 691.48, 583.5, 5...
Ciência da Computação                    [612.02, 646.8, 602.54, 619.28, 622.68, 607.48...
Ciências                                                                          [564.84]
Ciências Aeronáuticas                    [704.18, 692.3, 610.0, 718.12, 611.3, 600.4, 6...
Ciências Atuariais                                                        [634.24, 658.02]
                                                               ...
Segurança Pública                        [601.96, 551.38, nan, 639.36, 543.9, 571.48, 5...
Segurança da Informação                  [610.02, 650.34, 690.3, 557.26, 550.66, 597.54...
Segurança no Trabalho                    [571.24, 625.96, 520.16, nan, 603.74, 524.66, ...
Segurança no Trânsito                    [538.2, nan, 508.4, 571.06, 531.2, 585.76, 555...
Serviço Social                           [547.56, nan, 626.72, 612.9, 503.64, 576.08, 5...
Serviços Jurídicos                                                        [551.08, 527.58]
Serviços Jurídicos e Notariais               [477.96, 466.7, 573.66, 628.66, 614.7, 500.5]
Serviços Penais                                                                   [548.54]
Sistema de Informação                    [619.38, 587.6, 619.84, nan, 590.4, 577.5, 645...
Sistemas Automotivos                                                              [570.54]
Sistemas Biomédicos                                                               [599.74]
Sistemas de Informação                   [nan, 642.32, 561.88, 604.56, 606.88, 539.12, ...
Sistemas de Segurança Pública                                                     [580.38]
Sistemas de Telecomunicações                                                       [580.5]
Sistemas para Internet                   [580.28, 591.46, 582.52, 626.74, nan, 568.32, ...
Sociologia                               [517.28, nan, 554.4, 535.88, 549.82, 450.0, 54...
Soldagem                                                                  [581.92, 557.04]
Teatro                                             [634.72, 660.28, 649.04, 620.2, 630.04]
Tecnologia em Engenharia                                                          [531.62]
Tecnólogo em Metalurgia                                                    [525.6, 583.84]
Teologia                                 [nan, 572.6, 592.54, 592.12, 450.0, 629.82, 57...
Terapia Ocupacional                      [651.98, 606.3, nan, 560.08, 560.58, 608.48, 6...
Tradutor e Intérprete                      [525.3, 640.48, 558.16, 654.84, 630.68, 579.56]
Turismo                                  [582.06, 587.86, 548.16, 572.88, 528.32, 547.0...
Turismo Receptivo                          [573.78, 578.5, 536.36, 532.66, 515.86, 508.12]
Turismo e Hotelaria                                                               [559.12]
Visagismo e Terapias Capilares                                            [564.12, 608.48]
Viticultura e Enologia                                                    [522.52, 502.08]
Zootecnia                                [633.02, 569.46, 610.4, 612.96, 624.76, 583.68...
Óptica e Optometria                                                       [584.84, 656.82]
Name: nota_integral_ampla, Length: 296, dtype: object

**4. Find rows (with all columns) that have the highest `mensalidade` per `uf_busca`**

For request all columns in one row, it's necessary use the dataframe method `loc()` that find rows (by label name) from a condition (`groupby`, for example)

In [3]:
data.loc[data.groupby('uf_busca')['mensalidade'].idxmax()]

,uf_busca,cidade_busca,universidade_nome,campus_nome,nome,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
31940,AC,Rio Branco,Faculdade Barão do Rio Branco - FAB,CAMPUS - RIO BRANCO - JARDIM EUROPA II - Jard...,Medicina,Bacharelado,Integral,9674.34,4.0,1.0,5.0,2.0,758.32,723.94,734.92,711.26
31941,AL,Maceio,Centro Universitário Tiradentes - FITS,CAMPUS - MACEIÓ - CRUZ DAS ALMAS - Cruz das A...,Medicina,Bacharelado,Integral,7290.00,5.0,2.0,NaN,NaN,753.02,735.26,NaN,NaN
32962,AM,Manaus,Faculdade Uninassau Manaus,FACULDADE SANTA DOROTEIA DO AMAZONAS - Nossa S...,Odontologia,Bacharelado,Matutino,2127.05,4.0,1.0,NaN,NaN,639.22,628.52,NaN,NaN
32966,AP,Macapa,Instituto Macapaense de Ensino Superior - IMMES,CAMPUS - MACAPÁ - CENTRO - Centro,Odontologia,Bacharelado,Noturno,3607.62,0.0,1.0,NaN,1.0,690.32,NaN,620.44,NaN
31945,BA,Lauro de Freitas,Faculdade de Ciências Agrárias e da Saúde - FAS,UNIDADE SEDE - Centro,Medicina,Bacharelado,Integral,9048.00,13.0,4.0,NaN,NaN,741.04,730.36,NaN,NaN
12916,CE,Crateus,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,Enfermagem,Bacharelado,Noturno,9836.40,1.0,NaN,NaN,NaN,663.36,NaN,NaN,NaN
31950,DF,Brasilia,Faculdades Integradas da União Educacional do ...,UNIDADE GAMA - Setor Leste Gama,Medicina,Bacharelado,Integral,6757.92,8.0,7.0,NaN,NaN,745.58,731.24,NaN,NaN
31952,ES,Colatina,Centro Universitário do Espírito Santo - Unesc...,UNIDADE SEDE - Martinelli,Medicina,Bacharelado,Integral,6022.28,NaN,NaN,3.0,3.0,NaN,NaN,750.02,727.00
31957,GO,Goiania,Pontifícia Universidade Católica de Goiás - PU...,GOIÂNIA (SEDE) - SETOR UNIVERSITÁRIO,Medicina,Bacharelado,Integral,6484.47,3.0,2.0,NaN,NaN,763.24,749.98,NaN,NaN
31959,MA,Imperatriz,Universidade do Ceuma - Uniceuma - UNICEUMA,UNIVERSIDADE DO CEUMA - UNICEUMA - CAMPUS IMPE...,Medicina,Bacharelado,Integral,8281.38,3.0,1.0,6.0,2.0,756.46,737.88,747.14,717.60
31983,MG,Sao Joao Del Rei,Centro Universitário Presidente Tancredo de Al...,UNIDADE SEDE (UNIDADE) - Fábricas,Medicina,Bacharelado,Integral,9350.00,4.0,3.0,NaN,NaN,747.84,736.68,NaN,NaN
31987,MS,Campo Grande,Universidade Anhanguera - UNIDERP,CAMPO GRANDE - SEDE - Miguel Couto,Medicina,Bacharelado,Integral,9999.99,15.0,14.0,NaN,NaN,740.22,726.46,NaN,NaN
31988,MT,Cuiaba,Universidade de Cuiabá - UNIC/UNIME,UNIC - BEIRA RIO (SEDE) - Jardim Europa,Medicina,Bacharelado,Integral,9208.00,7.0,5.0,NaN,NaN,735.40,725.36,NaN,NaN
31990,PA,Belem,Faculdade Metropolitana da Amazônia - FAMAZ,FACULDADE METROPOLITANA DA AMAZÔNIA - FAMAZ - ...,Medicina,Bacharelado,Integral,8508.54,2.0,1.0,7.0,2.0,741.36,739.90,760.80,715.10
31995,PB,Joao Pessoa,Faculdade de Medicina Nova Esperança - FAMENE,CAMPUS - JOÃO PESSOA - Gramame,Medicina,Bacharelado,Integral,8350.00,4.0,3.0,NaN,NaN,759.76,736.94,NaN,NaN
31997,PE,Olinda,Faculdade de Medicina de Olinda - FMO,OLINDA-BAIRRO NOVO - Bairro Novo,Medicina,Bacharelado,Integral,7250.00,3.0,2.0,NaN,NaN,748.88,733.34,NaN,NaN
32001,PI,Parnaiba,"Faculdade de Ciências Humanas,Exatas e da Saúd...",CAMPUS PRINCIPAL / FAHESP- FACULDADE DE CIÊNCI...,Medicina,Bacharelado,Integral,8402.00,4.0,1.0,NaN,NaN,772.82,739.86,NaN,NaN
11916,PR,Curitiba,Faculdade Dom Bosco - FDB,UNIDADE MERCÊS - Mercês,Educação Física,Licenciatura,Matutino,8466.72,1.0,2.0,NaN,NaN,579.20,570.40,NaN,NaN
32012,RJ,Itaperuna,Faculdade Redentor - FACREDENTOR,CAMPUS - ITAPERUNA - PRESIDENTE COSTA E SILVA...,Medicina,Bacharelado,Integral,9023.07,4.0,4.0,5.0,5.0,741.06,729.02,730.98,722.82
32017,RN,Natal,Universidade Potiguar - UNP,CAMPUS NATAL - UNIDADE SALGADO FILHO - Lagoa Nova,Medicina,Bacharelado,Integral,6505.09,10.0,8.0,NaN,NaN,750.88,740.50,NaN,NaN
32019,RO,Porto Velho,Centro Universitário São Lucas - UniSL,CAMPUS - PORTO VELHO - AREAL - Areal,Medicina,Bacharelado,Integral,6909.97,4.0,3.0,9.0,5.0,742.72,720.20,729.72,711.68
33143,RR,Boa VIsta,Faculdade Cathedral - FACES,CAMPUS - BOA VISTA - CAÇARI - Caçari,Odontologia,Bacharelado,Integral,1463.05,2.0,1.0,3.0,1.0,685.20,675.74,609.98,573.48
32022,RS,Caxias do Sul,Universidade de Caxias do Sul - UCS,CAMPUS SEDE - Petrópolis,Medicina,Bacharelado,Integral,8329.95,1.0,4.0,NaN,NaN,745.42,751.32,NaN,NaN
32036,SC,Rio do Sul,Centro Universitário para O Desenvolvimento do...,CAMPUS DE RIO DO SUL - SEDE - Jardim América,Medicina,Bacharelado,Integral,6922.15,0.0,3.0,NaN,NaN,735.66,NaN,NaN,NaN
32038,SE,Aracaju,Universidade Tiradentes - UNIT,CAMPUS ARACAJU FAROLÂNDIA - Farolândia,Medicina,Bacharelado,Integral,6490.00,5.0,2.0,NaN,NaN,753.04,742.36,NaN,NaN
32058,SP,Sao Paulo,Universidade Cidade de São Paulo - UNICID,UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...,Medicina,Bacharelado,Integral,9715.61,2.0,5.0,6.0,10.0,739.62,738.08,738.96,718.64
32062,TO,Palmas,"Faculdade de Ciências Humanas, Econômicas e da...","FACULDADE DE CIÊNCIAS HUMANAS, ECONÔMICAS E DA...",Medicina,Bacharelado,Integral,7800.00,4.0,1.0,NaN,NaN,747.68,737.96,NaN,NaN